# Generated by Django 4.1.3 on 2022-11-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=50, verbose_name="Senha"),
        ),
    ]
